module.exports = {
  MAP_CENTER: '[40.7055585, -73.989109 ]',
  MAP_ZOOM: 13,
  TILE_LAYER: 'https://stamen-tiles-{s}.a.ssl.fastly.net/toner/{z}/{x}/{y}.png',
  DEFAULT_CITY: "New York",
  SHOW_FLAGGED_PLACES: false,
  SHOW_NO_MEMORY_PLACES: true,
  SUBHEADER_TEXT: process.env.SUBHEADER_TEXT,
  SUBHEADER_HREF: process.env.SUBHEADER_HREF,
  SUBHEADER_LINK_TEXT: process.env.SUBHEADER_LINK_TEXT,
  BRAND_TEXT_COLOR: process.env.BRAND_TEXT_COLOR,
  BRAND_CREATE_BUTTON: process.env.BRAND_CREATE_BUTTON,
  BRAND_CREATE_BUTTON_HOVER: process.env.BRAND_CREATE_BUTTON_HOVER,
  BRAND_HEADER_TEXT_COLOR: process.env.BRAND_HEADER_TEXT_COLOR
}
